{% set name = "hyperdiv" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyperdiv-{{ version }}.tar.gz
  sha256: 163db23ce739f01cd8827cb70cdf28f90fed4ee67844b48c32039949646dceeb

build:
  entry_points:
    - hyperdiv = hyperdiv.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - tornado >=6.1.0,<7.0.0
    - python-xxhash >=3.0.0,<4.0.0
    - click >=8.1.3,<9.0.0
    - cachetools >=5.3.0,<6.0.0
    - mistune >=2.0.5,<3.0.0
    - jinja2 >=3.1.2,<4.0.0
    - termcolor >=2.3.0,<3.0.0
    - email-validator >=2.0.0,<3.0.0
    - frozendict >=2.3.10,<3.0.0
    - parse >=1.20.0,<2.0.0
    - pygments >=2.17.2,<3.0.0

test:
  imports:
    - hyperdiv
  commands:
    - pip check
    - hyperdiv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hyperdiv.io/
  dev_url: https://github.com/hyperdiv/hyperdiv
  summary: Build reactive web UIs in pure Python
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - hyperdiv/hyperdiv-docs/LICENSE
    - hyperdiv/public/build/shoelace/assets/icons/LICENSE

extra:
  recipe-maintainers:
    - thewchan
